
alter table STORE_ORDER ALTER COLUMN BU_TIMEZONE TYPE character varying(50);
alter table STORE_ORDER_HIST ALTER COLUMN BU_TIMEZONE TYPE character varying(50);

ALTER TABLE STORE_ORDER ALTER COLUMN reference_timestamp TYPE TIMESTAMPTZ;
ALTER TABLE STORE_ORDER ALTER COLUMN create_timestamp TYPE TIMESTAMPTZ;
ALTER TABLE STORE_ORDER ALTER COLUMN change_timestamp TYPE TIMESTAMPTZ;

ALTER TABLE STORE_ORDER_HIST ALTER COLUMN reference_timestamp TYPE TIMESTAMPTZ;
ALTER TABLE STORE_ORDER_HIST ALTER COLUMN create_timestamp TYPE TIMESTAMPTZ;
ALTER TABLE STORE_ORDER_HIST ALTER COLUMN change_timestamp TYPE TIMESTAMPTZ;

ALTER TABLE STORE_ORDER_ITEM ALTER COLUMN contract_start_date TYPE TIMESTAMPTZ;
ALTER TABLE STORE_ORDER_ITEM ALTER COLUMN contract_end_date TYPE TIMESTAMPTZ;
ALTER TABLE STORE_ORDER_ITEM ALTER COLUMN create_timestamp TYPE TIMESTAMPTZ;
ALTER TABLE STORE_ORDER_ITEM ALTER COLUMN change_timestamp TYPE TIMESTAMPTZ;

ALTER TABLE STORE_ORDER_ITEM_HIST ALTER COLUMN contract_start_date TYPE TIMESTAMPTZ;
ALTER TABLE STORE_ORDER_ITEM_HIST ALTER COLUMN contract_end_date TYPE TIMESTAMPTZ;
ALTER TABLE STORE_ORDER_ITEM_HIST ALTER COLUMN create_timestamp TYPE TIMESTAMPTZ;
ALTER TABLE STORE_ORDER_ITEM_HIST ALTER COLUMN change_timestamp TYPE TIMESTAMPTZ;